SDSDemo/Models/RecyclableItem.cs
namespace SDSDemo.Models
{
    public class RecyclableItem
    {
        public int Id { get; set; }
        public int RecyclableTypeId { get; set; }
        public decimal Weight { get; set; }
        public decimal ComputedRate { get; set; }
        public string ItemDescription { get; set; }
        public virtual RecyclableType RecyclableType { get; set; }
    }
}

SDSDemo/Controllers/RecyclableItemController.cs
using SDSDemo.Interfaces;
using SDSDemo.Models;
using System.Web.Mvc;

namespace SDSDemo.Controllers
{
    public class RecyclableItemController : Controller
    {
        private readonly IRecyclableItemRepository _recyclableItemRepository;
        private readonly IRecyclableTypeRepository _recyclableTypeRepository;

        public RecyclableItemController(IRecyclableItemRepository recyclableItemRepository, IRecyclableTypeRepository recyclableTypeRepository)
        {
            _recyclableItemRepository = recyclableItemRepository;
            _recyclableTypeRepository = recyclableTypeRepository;
        }

        public ActionResult Index()
        {
            var recyclableItems = _recyclableItemRepository.GetAll();
            return View(recyclableItems);
        }

        public ActionResult Details(int id)
        {
            var recyclableItem = _recyclableItemRepository.GetById(id);
            if (recyclableItem == null)
                return HttpNotFound();

            return View(recyclableItem);
        }

        public ActionResult Create()
        {
            ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecyclableItem recyclableItem)
        {
            var recyclableType = _recyclableTypeRepository.GetById(recyclableItem.RecyclableTypeId);

            if (recyclableType == null)
            {
                ModelState.AddModelError("", "Invalid Recyclable Type.");
                ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type");
                return View(recyclableItem);
            }

            // Validate Weight
            if (recyclableItem.Weight < recyclableType.MinKg || recyclableItem.Weight > recyclableType.MaxKg)
            {
                ModelState.AddModelError("Weight", $"Weight must be between {recyclableType.MinKg} and {recyclableType.MaxKg} kg.");
                ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type");
                return View(recyclableItem);
            }

            recyclableItem.ComputedRate = recyclableType.Rate * recyclableItem.Weight;
            recyclableItem.ComputedRate = decimal.Round(recyclableItem.ComputedRate, 2);

            if (ModelState.IsValid)
            {
                _recyclableItemRepository.Add(recyclableItem);
                return RedirectToAction("Index");
            }

            ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type", recyclableItem.RecyclableTypeId);
            return View(recyclableItem);
        }

        public ActionResult Edit(int id)
        {
            var recyclableItem = _recyclableItemRepository.GetById(id);
            if (recyclableItem == null)
                return HttpNotFound();

            ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type", recyclableItem.RecyclableTypeId);
            return View(recyclableItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableItem recyclableItem)
        {
            var recyclableType = _recyclableTypeRepository.GetById(recyclableItem.RecyclableTypeId);

            if (recyclableType == null)
            {
                ModelState.AddModelError("", "Invalid Recyclable Type.");
                ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type", recyclableItem.RecyclableTypeId);
                return View(recyclableItem);
            }

            // Validate Weight
            if (recyclableItem.Weight < recyclableType.MinKg || recyclableItem.Weight > recyclableType.MaxKg)
            {
                ModelState.AddModelError("Weight", $"Weight must be between {recyclableType.MinKg} and {recyclableType.MaxKg} kg.");
                ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type", recyclableItem.RecyclableTypeId);
                return View(recyclableItem);
            }

            recyclableItem.ComputedRate = recyclableType.Rate * recyclableItem.Weight;
            recyclableItem.ComputedRate = decimal.Round(recyclableItem.ComputedRate, 2);

            if (ModelState.IsValid)
            {
                _recyclableItemRepository.Update(recyclableItem);
                return RedirectToAction("Index");
            }

            ViewBag.RecyclableTypeId = new SelectList(_recyclableTypeRepository.GetAll(), "Id", "Type", recyclableItem.RecyclableTypeId);
            return View(recyclableItem);
        }

        public ActionResult Delete(int id)
        {
            var recyclableItem = _recyclableItemRepository.GetById(id);
            if (recyclableItem == null)
                return HttpNotFound();

            return View(recyclableItem);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _recyclableItemRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSDemo/Controllers/RecyclableTypeController.cs
using SDSDemo.Interfaces;
using SDSDemo.Models;
using System.Web.Mvc;

namespace SDSDemo.Controllers
{
    public class RecyclableTypeController : Controller
    {
        private readonly IRecyclableTypeRepository _recyclableTypeRepository;

        public RecyclableTypeController(IRecyclableTypeRepository recyclableTypeRepository)
        {
            _recyclableTypeRepository = recyclableTypeRepository;
        }

        public ActionResult Index()
        {
            var recyclableTypes = _recyclableTypeRepository.GetAll();
            return View(recyclableTypes);
        }

        public ActionResult Details(int id)
        {
            var recyclableType = _recyclableTypeRepository.GetById(id);
            if (recyclableType == null)
                return HttpNotFound();

            return View(recyclableType);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecyclableType recyclableType)
        {
            // Custom validation
            if (recyclableType.MinKg <= 0 || recyclableType.MaxKg <= 0)
            {
                ModelState.AddModelError("MinKg", "MinKg and MaxKg must be greater than zero.");
                ModelState.AddModelError("MaxKg", "MinKg and MaxKg must be greater than zero.");
            }
            if (recyclableType.MinKg >= recyclableType.MaxKg)
            {
                ModelState.AddModelError("MaxKg", "MaxKg must be greater than MinKg.");
            }
            if (ModelState.IsValid)
            {
                _recyclableTypeRepository.Add(recyclableType);
                return RedirectToAction("Index");
            }

            return View(recyclableType);
        }

        public ActionResult Edit(int id)
        {
            var recyclableType = _recyclableTypeRepository.GetById(id);
            if (recyclableType == null)
                return HttpNotFound();

            return View(recyclableType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableType recyclableType)
        {
            // Custom validation
            if (recyclableType.MinKg <= 0 || recyclableType.MaxKg <= 0)
            {
                ModelState.AddModelError("MinKg", "MinKg and MaxKg must be greater than zero.");
                ModelState.AddModelError("MaxKg", "MinKg and MaxKg must be greater than zero.");
            }
            if (recyclableType.MinKg >= recyclableType.MaxKg)
            {
                ModelState.AddModelError("MaxKg", "MaxKg must be greater than MinKg.");
            }
            if (ModelState.IsValid)
            {
                _recyclableTypeRepository.Update(recyclableType);
                return RedirectToAction("Index");
            }

            return View(recyclableType);
        }

        public ActionResult Delete(int id)
        {
            var recyclableType = _recyclableTypeRepository.GetById(id);
            if (recyclableType == null)
                return HttpNotFound();

            return View(recyclableType);
        }

        [HttpGet]
        public ActionResult GetRateByTypeId(int id)
        {
            var recyclableType = _recyclableTypeRepository.GetById(id);
            if (recyclableType != null)
            {
                return Json(recyclableType.Rate, JsonRequestBehavior.AllowGet);
            }
            return Json(0, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _recyclableTypeRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSDemo/Views/RecyclableItem/Create.cshtml
@model SDSDemo.Models.RecyclableItem

@{
    ViewBag.Title = "Create";
}

<h2>Create Recyclable Item</h2>

<form id="createRecyclableItemForm" method="post">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recyclable Item</h4>
        <hr />
        <div class="form-group">
            @Html.Label("Recyclable Type", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RecyclableTypeId", (IEnumerable<SelectListItem>)ViewBag.RecyclableTypes, "Select Recyclable Type", new { @class = "form-control" })
                @Html.ValidationMessage("RecyclableTypeId")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription)
                @Html.ValidationMessageFor(model => model.ItemDescription)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Weight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight)
                @Html.ValidationMessageFor(model => model.Weight)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ComputedRate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComputedRate, new { @readonly = "readonly", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComputedRate)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-secondary" onclick="resetForm()">Reset Form</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Recalculate computed rate when weight or type changes
            $('#RecyclableTypeId, #Weight').on('change keyup', calculateComputedRate);

            function calculateComputedRate() {
                var typeId = $('#RecyclableTypeId').val();
                var weight = parseFloat($('#Weight').val());

                if (typeId && !isNaN(weight)) {
                    $.ajax({
                        url: '@Url.Action("GetRateByTypeId", "RecyclableType")',
                        contentType: "application/json; charset=utf-8",
                        data: { id: typeId },
                        dataType: "json",
                        success: function (data) {
                            var rate = parseFloat(data);
                            var computedRate = (weight * rate).toFixed(2);
                            $('#ComputedRate').val(computedRate);
                        },
                        error: function (xhr, status, error) {
                            console.error('Error occurred:', status, error);
                            $('#ComputedRate').val('');
                        }
                    });
                } else {
                    $('#ComputedRate').val('');
                }
            }
        });

        function resetForm() {
            // Clear all form fields
            $('#createRecyclableItemForm')[0].reset();

            // Clear validation messages
            $('.field-validation-error').html('');
            $('.input-validation-error').removeClass('input-validation-error');

            // Reset computed rate to empty
            $('#ComputedRate').val('');

            // Reset dropdown to the default option
            $('#RecyclableTypeId').val('');
            $('#Weight').val('');
            $('#ItemDescription').val('');

            // Optional: if using Select2 or other custom dropdowns, you may need to reset them separately
        }
    </script>
}

SDSDemo/Views/RecyclableItem/Edit.cshtml
@model SDSDemo.Models.RecyclableItem

@{
    ViewBag.Title = "Edit Recyclable Item";
}

<h2>Edit Recyclable Item</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recyclable Item</h4>
        <hr />
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.Label("Recyclable Type", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RecyclableTypeId", (IEnumerable<SelectListItem>)ViewBag.RecyclableTypes, "Select Recyclable Type", new { @class = "form-control", id = "RecyclableTypeDropdown" })
                @Html.ValidationMessage("RecyclableTypeId")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription)
                @Html.ValidationMessageFor(model => model.ItemDescription)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Weight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { @class = "form-control", id = "WeightInput" })
                @Html.ValidationMessageFor(model => model.Weight)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ComputedRate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ComputedRate, new { @class = "form-control", id = "ComputedRate", @disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.ComputedRate)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button type="button" class="btn btn-secondary" onclick="resetForm()">Reset Form</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            // Store initial values for reset
            var initialRecyclableTypeId = $('#RecyclableTypeDropdown').val();
            var initialItemDescription = $('#ItemDescription').val();
            var initialWeight = $('#Weight').val();
            var initialComputedRate = $('#ComputedRate').val();

            // Attach event handlers
            $('#RecyclableTypeDropdown, #Weight').on('change keyup', calculateComputedRate);

            function calculateComputedRate() {
                var typeId = $('#RecyclableTypeDropdown').val();
                var weight = parseFloat($('#Weight').val());

                if (typeId && !isNaN(weight)) {
                    $.ajax({
                        url: '@Url.Action("GetRateByTypeId", "RecyclableType")',
                        contentType: "application/json; charset=utf-8",
                        data: { id: typeId },
                        dataType: "json",
                        success: function (data) {
                            var rate = parseFloat(data);
                            var computedRate = (weight * rate).toFixed(2);
                            $('#ComputedRate').val(computedRate);
                        },
                        error: function (xhr, status, error) {
                            console.error('Error occurred:', status, error);
                            $('#ComputedRate').val('');
                        }
                    });
                } else {
                    $('#ComputedRate').val('');
                }
            }

            window.resetForm = function () {
                // Reset fields to their initial values
                $('#RecyclableTypeDropdown').val(initialRecyclableTypeId);
                $('#ItemDescription').val(initialItemDescription);
                $('#Weight').val(initialWeight);
                $('#ComputedRate').val(initialComputedRate);

                // Clear validation messages
                $('.field-validation-error').html('');
                $('.input-validation-error').removeClass('input-validation-error');
            }
        });
    </script>
}

SDSDemo/Views/RecyclableItem/Index.cshtml
@model IEnumerable<SDSDemo.Models.RecyclableItem>

@{
    ViewBag.Title = "Recyclable Items";
}

<h2>Recyclable Items</h2>

    @Html.AntiForgeryToken()

<p>
    @Html.ActionLink("Create New Recyclable Item", "Create")
</p>

<table class="table">
    <thead>
        <tr>
            <th>Recyclable Type</th>
            <th>Weight</th>
            <th>Computed Rate</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="item-@item.Id">
                <td>@item.RecyclableType.Type</td>
                <td>@item.Weight</td>
                <td>@item.ComputedRate</td>
                <td>@item.ItemDescription</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    <a href="#" class="text-danger" onclick="showDeleteRecyclableItemModal(@item.Id, '@item.ItemDescription', @item.Weight, @item.ComputedRate, '@item.RecyclableType.Type'); return false;">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="deleteRecyclableItemModal" tabindex="-1" role="dialog" aria-labelledby="deleteRecyclableItemModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteRecyclableItemModalLabel">Delete Recyclable Item</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="deleteRecyclableItemForm">
                <div class="modal-body">
                    <p>Are you sure you want to delete this recyclable item?</p>
                    <div id="recyclableItemDetails">
                        <!-- Details will be injected here by JavaScript -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="deleteRecyclableItem()">Delete</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var deleteId = 0; // Variable to store the ID of the item to delete

    function showDeleteRecyclableItemModal(id, description, weight, computedRate, recyclableTypeName) {
        deleteId = id;
        $('#recyclableItemDetails').html(
            `<strong>Item Description:</strong> ${description}<br />
             <strong>Weight:</strong> ${weight}<br />
             <strong>Computed Rate:</strong> ${computedRate}<br />
             <strong>Recyclable Type:</strong> ${recyclableTypeName}`
        );
        $('#deleteRecyclableItemModal').modal('show');
    }

    function deleteRecyclableItem() {
       
        $.ajax({
            url: '/RecyclableItem/Delete/' + deleteId, // URL to delete item
            type: 'POST',
            data: {
                __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() // Anti-forgery token
            },
            success: function (result) {
                // On success, remove the item from the table and close the modal
                $('#item-' + deleteId).remove();
                $('#deleteRecyclableItemModal').modal('hide');
            },
            error: function (xhr, status, error) {
                console.error('Error occurred:', status, error);
                alert('An error occurred while deleting the item.');
            }
        });
    }
</script>